---
title: "The Documentation of MicrobitaProcess package"
author: "Shuangbin Xu"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    toc: true
    theme: cayman
    highlight: github
  pdf_document:
    toc: true
---

# The example of `CountOrRatios` function

```{r}
source("../R/CountOrRatios.R")
otuda <- read.table("../data/otu_tax_table.txt",
                  sep="\t", header=T, row.names=1, check.names=F, comment.char="",skip=1)
tax <- otuda[,"taxonomy",drop=FALSE]
otuda$taxonomy <- NULL
otuda <- data.frame(t(otuda), check.names=F)
head(otuda[,1:7])
sampleda <- read.table("../data/sample_info.txt", header=T, row.names=1)
dat <- CountOrRatios(otuda, sampleda, countmode=TRUE,
                          percentmode=FALSE,
                          multiplenum=1,
                          rownamekeep=FALSE)
head(dat[,1:10])
```

# The example of `MultiGroupCompare` function 

## The multiple group compare for single feature.

```{r}
source("../R/MultiGroupCompare.R")
otumeta <- merge(otuda, sampleda, by=0)
rownames(otumeta) <- otumeta$Row.names
otumeta$Row.names <- NULL
OneFeatureTest <- MultiGroupCompare(data=otumeta,measure="OTU_1")
print(OneFeatureTest)
```

# The example of `mapplyMultiGroupCompare` function

## The multiple group compare for multiple feature. 

```{r, warning=FALSE}
multiFeatureTest <- mapplyMultiGroupCompare(data=otumeta,
											measurelist=c("OTU_1","OTU_10"),
											padjust="fdr")
print(multiFeatureTest)
totalFeatureTest <- dplyr::bind_rows(mapplyMultiGroupCompare(data=otumeta,
											padjust="fdr"))
head(totalFeatureTest)

```

# The example of `splitStrtoList` function

```{r}
source("../R/splitStrtoList.R")
head(tax, 3)
taxdat <- splitStrtoList(tax, prefix="tax", sep="; ")
head(taxdat, 3)
```

# The example of `droptax` function

```{r}
source("../R/droptax.R")
tax6da <- taxdat[,"tax6",drop=FALSE]
#genustab <- merge(t(otuda), tax6da, by=0)
#genustab$Row.names <- NULL
genustab <- CountOrRatios(da=data.frame(t(otuda),check.names=FALSE), 
			  featurelist=tax6da, countmode=TRUE,
			  rownamekeep=FALSE)
head(genustab, 3)
#print(sort(rowSums(genustab)))
dim(genustab)
# remove the few abundance and few occurrences
newgenustab <- droptax(genustab,rmode=TRUE, minocc=0.2, minabu=1)
head(newgenustab, 3)
dim(newgenustab)
#print()
```

# The example of `getvennlist` function 

```{r}
source("../R/getvennlist.R")
source("../R/CountOrRatios.R")
#otuda <- read.table("../data/otu_tax_table.txt",
#		      sep="\t", header=T, row.names=1, check.names=F, comment.char="",skip=1)
#tax <- otuda[,"taxonomy",drop=FALSE]
#otuda$taxonomy <- NULL
#otuda <- data.frame(t(otuda), check.names=F)
#head(otuda[,1:7])
#sampleda <- read.table("../data/sample_info.txt", header=T, row.names=1)
#head(sampleda)
vennlistda <- getvennlist(otuda, sampleda)
print(vennlistda)
```

